name: Make release
run-name: Make release
on: [workflow_dispatch]
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # get the version for the release
      - name: version
        run: >-
          echo "::set-output name=VERSION::$(
            cat VERSION
          )"
        id: version
      - name: Build
        run: cp README.md README-${{ steps.version.outputs.VERSION }}.md
      # get the MFP version for the release
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: actiontest ${{ steps.version.outputs.VERSION }}
          tag_name: v${{ steps.version.outputs.VERSION }}
          body_path: ANNOUNCE-${{ steps.version.outputs.VERSION }}.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Add built data to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: mfp_release_${{ steps.version.outputs.version }}
          asset_path: README-${{ steps.version.outputs.version }}.md
